ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/labsuser.pem

ansible_ssh_common_args: >
  -o ProxyCommand="ssh -i ~/.ssh/labsuser.pem -W %h:%p admin@{{ groups['nat_bastion'][0] }}"

hardening_sysctl:
  net.ipv4.ip_forward: 0
  net.ipv4.tcp_syncookies: 1
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.default.send_redirects: 0
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.default.accept_source_route: 0

hardening_ssh_allow_tcp_forwarding: "no"
hardening_ssh_x11_forwarding: "no"
