---
cowrie_user: cowrie
cowrie_home: /home/cowrie
cowrie_repo: https://github.com/cowrie/cowrie.git
cowrie_hostname: prod-order-api
cowrie_listen_port: 22
cowrie_listen_interface: 0.0.0.0
ssh_real_port: 2222

# Dependencias del sistema
cowrie_system_packages:
  - python3-pip
  - python3-venv
  - git
  - openssl
  - libssl-dev
  - zlib1g-dev
  - authbind