---
- name: restart ssh
  systemd:
    name: ssh
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart cowrie
  systemd:
    name: cowrie
    state: restarted

# - name: restart ssh
#   systemd:
#     name: ssh
#     state: restarted
#   async: 0
#   poll: 0
