---
hardening_admin_user: "admin"

# SSH hardening
hardening_ssh_port: 22
hardening_ssh_allow_tcp_forwarding: "yes"   # En bastion a veces se usa forwarding. Si lo necesitas, pon "yes".
hardening_ssh_x11_forwarding: "no"
hardening_ssh_max_auth_tries: 3
hardening_ssh_client_alive_interval: 300
hardening_ssh_client_alive_count_max: 2

# Servicios a deshabilitar si existen (ajusta según tu AMI)
hardening_disable_services:
  - avahi-daemon
  - cups
  - bluetooth
  - rpcbind
  - nfs-server
  - nfs-kernel-server

# Sysctl básico (breve y razonable)
hardening_sysctl:
  net.ipv4.ip_forward: 1                # OJO: para NAT/Bastion suele ser necesario. Si es otro host, pon 0.
  net.ipv4.tcp_syncookies: 1
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.default.accept_redirects: 0
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.default.send_redirects: 0
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1
  net.ipv4.conf.all.accept_source_route: 0
  net.ipv4.conf.default.accept_source_route: 0
  net.ipv6.conf.all.disable_ipv6: 1

