# ============================================
# Playbook para desplegar Honeypots
# ============================================

---
- name: Desplegar Cowrie SSH Honeypot
  hosts: popbl-grupo1-cowrie-Honeypot
  become: yes
  gather_facts: yes
  
  roles:
    - cowrie
    - fluentbit-honeypots

- name: Deploy Dionaea Honeypot
  hosts: popbl-grupo1-dionaea-Honeypot
  become: yes
  gather_facts: yes

  roles:
    - dionaea
    - fluentbit-honeypots